### ISSUE TITLE
Error in atexit._run_exitfuncs and ERROR: Unauthorized 401

### ISSUE THREAD

**Issue by szanyi** [PocketCoffea/PocketCoffea#168]
Hi

I am trying to run the Z->\mu\mu full analysis example on lxplus7 but I get error messages. 

Executing **runner.py --cfg example_config.py --test  -o output_test**, I get

```
(myenv) Singularity> runner.py --cfg example_config.py --test  -o output_test
Loading the configuration file...
Traceback (most recent call last):
  File "/afs/cern.ch/user/i/iszanyi/PocketCoffea/myenv/bin/runner.py", line 33, in <module>
    sys.exit(load_entry_point('pocket-coffea', 'console_scripts', 'runner.py')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/afs/cern.ch/user/i/iszanyi/PocketCoffea/pocket_coffea/scripts/runner.py", line 74, in run
    config = load_config(cfg, outputdir)
  File "/afs/cern.ch/user/i/iszanyi/PocketCoffea/pocket_coffea/scripts/runner.py", line 23, in load_config
    config_module =  utils.path_import(cfg)
  File "/afs/cern.ch/user/i/iszanyi/PocketCoffea/pocket_coffea/utils/utils.py", line 27, in path_import
    raise Exception(f"Module path {absolute_path} not found!")
Exception: Module path example_config.py not found!
(myenv) Singularity> cd AnalysisConfigs/configs/zmumu/
(myenv) Singularity> runner.py --cfg example_config.py --test  -o output_test
Loading the configuration file...
[INFO    ] Configurator instance:
  - Workflow: <class 'workflow.ZmumuBaseProcessor'>
  - Workflow options: {}
  - N. datasets: 5
   -- Dataset: DATA_SingleMuon_2018_EraA,  Sample: DATA_SingleMuon, N. files: 92, N. events: 241608232
   -- Dataset: DATA_SingleMuon_2018_EraB,  Sample: DATA_SingleMuon, N. files: 51, N. events: 119918017
   -- Dataset: DATA_SingleMuon_2018_EraC,  Sample: DATA_SingleMuon, N. files: 56, N. events: 109986009
   -- Dataset: DATA_SingleMuon_2018_EraD,  Sample: DATA_SingleMuon, N. files: 194, N. events: 513909894
   -- Dataset: DYJetsToLL_M-50_2018,  Sample: DYJetsToLL, N. files: 204, N. events: 195510810
  - Subsamples:
   -- Sample DATA_SingleMuon: StandardSelection ['DATA_SingleMuon'], (1 categories)
   -- Sample DYJetsToLL: StandardSelection ['DYJetsToLL'], (1 categories)
  - Skim: ['nMuon_min1_pt18.0', 'HLT_trigger_SingleMuon']
  - Preselection: ['dilepton']
  - Categories: StandardSelection ['baseline'], (1 categories)
  - Variables:  ['MuonGood_eta_1', 'MuonGood_pt_1', 'MuonGood_phi_1', 'nElectronGood',
'nMuonGood', 'nJets', 'nBJets', 'JetGood_eta_1', 'JetGood_pt_1',
'JetGood_phi_1', 'JetGood_btagDeepFlavB_1', 'JetGood_btagDeepFlavCvL_1',
'JetGood_btagDeepFlavCvB_1', 'JetGood_eta_2', 'JetGood_pt_2', 'JetGood_phi_2',
'JetGood_btagDeepFlavB_2', 'JetGood_btagDeepFlavCvL_2',
'JetGood_btagDeepFlavCvB_2', 'mll']
  - Columns: {'DATA_SingleMuon': {'baseline': []}, 'DYJetsToLL': {'baseline': []}}
  - available weights variations: {'DATA_SingleMuon': ['pileup', 'sf_mu_id', 'nominal', 'sf_mu_iso'],
'DYJetsToLL': ['pileup', 'sf_mu_id', 'nominal', 'sf_mu_iso']}
  - available shape variations: {'DATA_SingleMuon': [], 'DYJetsToLL': []}
Saving config file to output_test/config.json
Running with executor iterative None
Working on sample: DATA_SingleMuon_2018_EraA
[INFO    ] Working on sample: DATA_SingleMuon_2018_EraA
Preprocessing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:04 < 0:00:00 | 0.5 file/s ]
Processing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:17 < 0:00:00 | 0.1 chunk/s ]
Saving output to output_test/output_DATA_SingleMuon_2018_EraA.coffea
Working on sample: DATA_SingleMuon_2018_EraB
[INFO    ] Working on sample: DATA_SingleMuon_2018_EraB
Preprocessing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:03 < 0:00:00 | 0.8 file/s ]
Processing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:12 < 0:00:00 | 0.2 chunk/s ]
Saving output to output_test/output_DATA_SingleMuon_2018_EraB.coffea
Working on sample: DATA_SingleMuon_2018_EraC
[INFO    ] Working on sample: DATA_SingleMuon_2018_EraC
Preprocessing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:03 < 0:00:00 | 0.7 file/s ]
Processing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:17 < 0:00:00 | 0.1 chunk/s ]
Saving output to output_test/output_DATA_SingleMuon_2018_EraC.coffea
Working on sample: DATA_SingleMuon_2018_EraD
[INFO    ] Working on sample: DATA_SingleMuon_2018_EraD
Preprocessing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:03 < 0:00:00 | 0.6 file/s ]
Processing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:14 < 0:00:00 | 0.1 chunk/s ]
Saving output to output_test/output_DATA_SingleMuon_2018_EraD.coffea
Working on sample: DYJetsToLL_M-50_2018
[INFO    ] Working on sample: DYJetsToLL_M-50_2018
Preprocessing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:02 < 0:00:00 | 0.6 file/s ]
Processing 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ 0:00:12 < 0:00:00 | 0.2 chunk/s ]
Saving output to output_test/output_DYJetsToLL_M-50_2018.coffea
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/XRootD/client/finalize.py", line 45, in finalize
    if isinstance(obj, File) and obj.is_open():
ReferenceError: weakly-referenced object no longer exists
```

Then executing **runner.py --cfg example_config.py  --full --executor dask@lxplus --run-options custom_run_options.yaml  -o output_dask** , I get

```
[ERROR   ] Task exception was never retrieved
future: <Task finished name='Task-8797' coro=<_wrap_awaitable() done, defined at /usr/local/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('Command exited with non-zero exit code.\nExit code: 1\nCommand:\ncondor_submit /tmp/iszanyi/tmp629ryyay.sh\nstdout:\n\nstderr:\n2024/05/20 01:32:51 ERROR: Unauthorized 401 - do you have authentication tokens?\nError "/usr/bin/myschedd.sh |": command terminated with exit code 256\nConfiguration Error Line 0 while reading config source /usr/bin/myschedd.sh |\n\n')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 59, in _
    await self.start()
  File "/usr/local/lib/python3.8/site-packages/dask_jobqueue/core.py", line 325, in start
    out = await self._submit_job(fn)
  File "/usr/local/lib/python3.8/site-packages/dask_jobqueue/core.py", line 308, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/usr/local/lib/python3.8/site-packages/dask_jobqueue/core.py", line 403, in _call
    raise RuntimeError(
RuntimeError: Command exited with non-zero exit code.
Exit code: 1
Command:
condor_submit /tmp/iszanyi/tmp629ryyay.sh
stdout:

stderr:
2024/05/20 01:32:51 ERROR: Unauthorized 401 - do you have authentication tokens?
Error "/usr/bin/myschedd.sh |": command terminated with exit code 256
Configuration Error Line 0 while reading config source /usr/bin/myschedd.sh |


[ERROR   ] Task exception was never retrieved
future: <Task finished name='Task-8795' coro=<_wrap_awaitable() done, defined at /usr/local/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('Command exited with non-zero exit code.\nExit code: 1\nCommand:\ncondor_submit /tmp/iszanyi/tmpfnark_ah.sh\nstdout:\n\nstderr:\n2024/05/20 01:32:51 ERROR: Unauthorized 401 - do you have authentication tokens?\nError "/usr/bin/myschedd.sh |": command terminated with exit code 256\nConfiguration Error Line 0 while reading config source /usr/bin/myschedd.sh |\n\n')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 59, in _
    await self.start()
  File "/usr/local/lib/python3.8/site-packages/dask_jobqueue/core.py", line 325, in start
    out = await self._submit_job(fn)
  File "/usr/local/lib/python3.8/site-packages/dask_jobqueue/core.py", line 308, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/usr/local/lib/python3.8/site-packages/dask_jobqueue/core.py", line 403, in _call
    raise RuntimeError(
RuntimeError: Command exited with non-zero exit code.
Exit code: 1
Command:
condor_submit /tmp/iszanyi/tmpfnark_ah.sh
stdout:

stderr:
2024/05/20 01:32:51 ERROR: Unauthorized 401 - do you have authentication tokens?
Error "/usr/bin/myschedd.sh |": command terminated with exit code 256
Configuration Error Line 0 while reading config source /usr/bin/myschedd.sh |
```
What could be the problem?

Thanks in advance. 

Best regards, 
Istvan

**Comment by valsdav** [comment]
Hi! Can you please try with lxplus9 and with this command? 

```
apptainer shell -B /afs -B /cvmfs/cms.cern.ch \
                -B /tmp  -B /eos/cms/  -B /etc/sysconfig/ngbauth-submit \
                -B ${XDG_RUNTIME_DIR}  --env KRB5CCNAME="FILE:${XDG_RUNTIME_DIR}/krb5cc" 
    /cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-analysis/general/pocketcoffea:lxplus-cc7-stable
```

https://pocketcoffea.readthedocs.io/en/latest/installation.html#using-apptainer-to-run-the-analysis

The error is related to missing certificates to connect to condor in the apptainer image.

**Comment by valsdav** [comment]
Sorry I meant to try the `latest` image: 

```
apptainer shell -B /afs -B /cvmfs/cms.cern.ch \
                -B /tmp  -B /eos/cms/  -B /etc/sysconfig/ngbauth-submit \
                -B ${XDG_RUNTIME_DIR}  --env KRB5CCNAME="FILE:${XDG_RUNTIME_DIR}/krb5cc" 
    /cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-analysis/general/pocketcoffea:lxplus-cc7-latest
```
The `stable` version will move to the latest today.

**Comment by valsdav** [comment]
I just checked and the processing was fine for me.
 
Can you please list exactly your commands or contact me on mattermost?

**Comment by valsdav** [comment]
Resolved after changing lxplus machine. The apptainer image was not able to contact condor.
