### ISSUE TITLE
Output parquet files can have different schema

### ISSUE THREAD

**Issue by mmarchegiani** [PocketCoffea/PocketCoffea#272]
When using the `dump_columns_as_arrays_per_chunk` to save ntuples into a parquet file for each chunk, the output parquet files do not always have the same parquet schema.
When the `ak.to_parquet.dataset(folder)` function is called to save the metadata of the parquet files, the following error can appear for certain datasets:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/afs/cern.ch/work/m/mmarcheg/ttHbb/ttHbb_SPANet/../../AnalysisConfigs/configs/ttHbb/semileptonic/sig_bkg_classifier/create_parquet.py", line 27, in create_parquet_metadata
    ak.to_parquet.dataset(dataset_path)
  File "/afs/cern.ch/work/m/mmarcheg/ttHbb/envs/dctr/lib/python3.9/site-packages/awkward/operations/convert.py", line 3153, in _to_parquet_dataset
    pyarrow.parquet.write_metadata(
  File "/afs/cern.ch/work/m/mmarcheg/ttHbb/envs/dctr/lib/python3.9/site-packages/pyarrow/parquet/core.py", line 2247, in write_metadata
    metadata.append_row_groups(m)
  File "pyarrow/_parquet.pyx", line 1047, in pyarrow._parquet.FileMetaData.append_row_groups
RuntimeError: AppendRowGroups requires equal schemas.
The two columns with index 1 differ.
column descriptor = {
  name: element,
  path: JetGood_pt.list.element,
  physical_type: FLOAT,
  converted_type: NONE,
  logical_type: None,
  max_definition_level: 1,
  max_repetition_level: 1,
}
column descriptor = {
  name: item,
  path: JetGood_pt.list.item,
  physical_type: FLOAT,
  converted_type: NONE,
  logical_type: None,
  max_definition_level: 1,
  max_repetition_level: 1,
}
```
This happens because the parquet schema can vary across different files (for different chunks).
The nature of this issue is still unknown and could be due to None values in the ntuples, too small files (the affected datasets have parquet files with as low as ~10 events).
In order to solve the issue, the parquet schema should be enforced when the parquet files are created.

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

To address the issue of inconsistent parquet schemas across different chunks, we'll modify the `ColumnsManager` class to enforce a consistent schema when creating parquet files. We'll add a new method `get_parquet_schema` to define the schema, and update the `fill_ak_arrays` method to use this schema when creating the output.

I also created pull request: https://github.com/PocketCoffea/PocketCoffea/pull/273


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
