### ISSUE TITLE
Bug in build_dataset.py script related to metadata

### ISSUE THREAD

**Issue by mmarchegiani** [PocketCoffea/PocketCoffea#48]
In order to reproduce the error on the t3 machine:
- Move to the `PocketCoffea` folder
- Make sure that the following files **do not already exist** in the `PocketCoffea/datasets` folder: `DATA_BTagMu.json`, `DATA_BTagMu_local.json`, `MC_QCD_MuEnriched.json`, `MC_QCD_MuEnriched_local.json`
- Run with this command: `python scripts/dataset/build_dataset.py --cfg /work/mmarcheg/BTVNanoCommissioning/datasets/datasets_definitions_UL.json`

The following error will appear:
```
Traceback (most recent call last):
  File "scripts/dataset/build_dataset.py", line 46, in <module>
    dataset.save(overwrite=args.overwrite, split=args.split_by_year)
  File "/work/mmarcheg/PocketCoffea/pocket_coffea/utils/dataset.py", line 146, in save
    self._write_dataset(outfile, sample_dict, append, overwrite)
  File "/work/mmarcheg/PocketCoffea/pocket_coffea/utils/dataset.py", line 129, in _write_dataset
    raise Exception(
Exception: Sample metadata already present in file datasets/MC_QCD_MuEnriched.json, not overwriting!
```

**Comment by mmarchegiani** [comment]
The issue was solved in this commit: https://github.com/PocketCoffea/PocketCoffea/commit/4276caee8b30350a81c3b63c7876f6410c5ef8ca
